config/routes.rb
GameLobby::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as=>"log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"  
  resources :users
  resources :sessions
  resources :games
  resources :clashes
  root :to => "games#index"

end

app/models/game.rb
require 'net/http'
require 'uri'
require 'json'

require "redispusher.rb"

class Game < ActiveRecord::Base
  validates :name, :presence=>true
  validates :site, :presence=>true
  validates :comm, :presence=>true
  
  has_many :clashes
  after_create :push_creation
  before_destroy :push_destruction
  
  def format_message message
    #   the post_form method below only takes a specific format for hashes.  First reformat the current message to make sure it fits 
    formatted_message = {}
    message.each_pair do |key,value|
      formatted_message[key.to_s] = value
    end
    
    return formatted_message
  end
  
  def communicate_with_game_server message
    #  separate out the host, port, and destination from the stored URI
    uri = URI.parse comm
    
    #  send out the POST    
    res = Net::HTTP.post_form(uri,message)
    if res.class == Net::HTTPSuccess or res.class == Net::HTTPRedirection or res.class == Net::HTTPOK
      result = JSON.parse res.body
      logger.info("Response: #{result}")
      return result
    end
    logger.error("Error Response:#{res.class}")
    return nil
  end
  
  def send_message message
    formatted_message = format_message message
    logger.info("Message to \"#{name}\": #{formatted_message}")
    
    return communicate_with_game_server formatted_message
  end
  
  def is_developer? user
    GameDeveloper.where(:game_id=>self.id,:user_id=>user.id).any?
  end
  
  def push_creation
    RedisPusher.push_data('games',{:type=>"new_game",:id=>self.id,:name=>self.name})
  end
  
  def push_destruction
    RedisPusher.push_data('games',{:type=>"game_gone",:id=>self.id,:name=>self.name})
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :load_game, :except => [ :index, :new, :create ]
  before_filter :ensure_logged_in, :except => [ :index, :show ]
  before_filter :ensure_is_developer, :only => [ :edit, :update, :destroy ]
  
  respond_to :html, :xml, :json
  
  def index
    @games = Game.all
    respond_with @games
  end
  
  def show
    respond_with @game
  end
  
  def new
    @game = Game.new
    respond_with @game
  end
  
  def create
    @game = Game.new params[:game]
    if @game.save
      GameDeveloper.create :game => @game, :user=>current_user
      respond_with @game
    else
      render 'new'
    end
  end
  
  def edit
    respond_with @game
  end
  
  def update
    if @game.update_attributes params[:game]
      respond_with @game
    else
      render 'edit'
    end
  end
  
  def destroy
    @game.destroy
    respond_with @game, :location => games_path
  end
  
  protected
  def load_game
    @game = Game.find params[:id]
    
    render :status => 404 if @game.nil?
  end
  
  def ensure_logged_in
    redirect_to games_path unless logged_in?
  end
  
  def ensure_is_developer
    redirect_to games_path unless @game.is_developer? current_user
  end
  
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= form_for @game do |f|
  - if @game.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        -for message in @game.errors.full_messages
          %li= message
  %p
    =f.label :name
    %br
    =f.text_field :name
  %p
    =f.label :site
    %br
    =f.text_field :site
  %p
    =f.label :comm
    %br
    =f.text_field :comm
  %p.button= f.submit @game.id.nil? ? "Make Game!" : "Adjust Game!"

app/views/games/edit.html.haml
=make_section "Edit Game Details" do
  =render :partial=>"form",:object=>@game,:as=>:game
  =button_to "Delete this game", game_path(@game), :method=>:delete

app/views/games/index.html.haml
=make_section "Game List",{:class=>'games list'} do
  %ul.games
    -for game in @games
      %li{:class => "game_#{game.id}"}
        =link_to game.name, game
  =link_to "Add New Game", new_game_path

app/views/games/new.html.haml
=make_section "New Game Info" do
  =render :partial=>'form',:object=>@game,:as=>'game'

app/views/games/show.html.haml
=make_section @game.name,{:class=>'game',:game_id=>@game.id} do
  -if current_user and @game.is_developer? current_user
    =make_section "Developer Info" do
      %p
        %b Website: 
        =" #{@game.site}"
      %p
        %b>Comm Channel: 
        =" #{@game.comm}"
      %p= link_to "Edit this game's info", edit_game_path(@game)
  =make_section "Clashes!" do
    %ul.clashes
      -for clash in @game.clashes.forming
        =link_to clash,{:class=>"clash#{clash.id}"} do
          %li= clash.name
    -if current_user
      %p
        =form_for Clash.new, :url=>clashes_path do |f|
          =f.hidden_field :game_id, :value=>@game.id
          =f.submit "New Clash!"
%p= link_to "Back to game list", games_path